export const mockProducts = [
    {
        id: "1",
        name: 'MacBook Pro 16"',
        description: "Powerful laptop for professionals",
        price: 2499.99,
        images: ["/macbook-pro.png", "/macbook-pro.png", "/macbook-pro.png"],
        category: "Laptops",
        stock: 12,
    },
    {
        id: "2",
        name: "iPhone 15 Pro",
        description: "Latest smartphone with advanced features",
        price: 999.99,
        images: ["/iphone-15-pro-hands.png", "/iphone-15-pro-hands.png", "/iphone-15-pro-hands.png"],
        category: "Phones",
        stock: 25,
    },
    {
        id: "3",
        name: "AirPods Pro",
        description: "Wireless earbuds with noise cancellation",
        price: 249.99,
        images: ["/airpods-pro-lifestyle.png", "/airpods-pro-lifestyle.png", "/airpods-pro-lifestyle.png"],
        category: "Audio",
        stock: 3,
    },
    {
        id: "4",
        name: "iPad Air",
        description: "Versatile tablet for work and entertainment",
        price: 599.99,
        images: ["/ipad-air-tablet.jpg", "/ipad-air-tablet.jpg", "/ipad-air-tablet.jpg"],
        category: "Tablets",
        stock: 8,
    },
    {
        id: "5",
        name: "Apple Watch Series 9",
        description: "Advanced smartwatch with fitness tracking",
        price: 399.99,
        images: ["/apple-watch-series-9.jpg", "/apple-watch-series-9.jpg", "/apple-watch-series-9.jpg"],
        category: "Wearables",
        stock: 15,
    },
    {
        id: "6",
        name: "Magic Keyboard",
        description: "Wireless keyboard with rechargeable battery",
        price: 299.99,
        images: ["/magic-keyboard.jpg", "/magic-keyboard.jpg", "/magic-keyboard.jpg"],
        category: "Accessories",
        stock: 0,
    },
    {
        id: "7",
        name: "USB-C Hub",
        description: "Multi-port adapter for connectivity",
        price: 79.99,
        images: ["/usb-c-hub.jpg", "/usb-c-hub.jpg", "/usb-c-hub.jpg"],
        category: "Accessories",
        stock: 42,
    },
    {
        id: "8",
        name: "Dell XPS 13",
        description: "Compact laptop with stunning display",
        price: 1299.99,
        images: ["/dell-xps-13-laptop.jpg", "/dell-xps-13-laptop.jpg", "/dell-xps-13-laptop.jpg"],
        category: "Laptops",
        stock: 6,
    },
]

export const mockOrders = [
    {
        id: "order-1",
        productId: "1",
        productName: 'MacBook Pro 16"',
        fullName: "John Doe",
        email: "john@example.com",
        phone: "+1 (555) 123-4567",
        quantity: 1,
        price: 2499.99,
        totalPrice: 2499.99,
        status: "confirmed",
        createdAt: new Date("2025-12-01"),
        updatedAt: new Date("2025-12-02"),
    },
    {
        id: "order-2",
        productId: "2",
        productName: "iPhone 15 Pro",
        fullName: "Jane Smith",
        email: "jane@example.com",
        phone: "+1 (555) 987-6543",
        quantity: 2,
        price: 999.99,
        totalPrice: 1999.98,
        status: "pending",
        createdAt: new Date("2025-12-03"),
        updatedAt: new Date("2025-12-03"),
    },
    {
        id: "order-3",
        productId: "3",
        productName: "AirPods Pro",
        fullName: "Mike Johnson",
        email: "mike@example.com",
        phone: "+1 (555) 456-7890",
        quantity: 1,
        price: 249.99,
        totalPrice: 249.99,
        status: "shipped",
        createdAt: new Date("2025-11-28"),
        updatedAt: new Date("2025-12-04"),
    },
]
